// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: ksyzeydfmpazkqrbqjmo

class SupabaseConfig {
  static const String supabaseUrl = 'https://ksyzeydfmpazkqrbqjmo.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzeXpleWRmbXBhemtxcmJxam1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1MzI5NTIsImV4cCI6MjA3NzEwODk1Mn0.ns2ADZkLrGvuIzWpeUbAU4STFs7mY5uh00hP4P2fl2Q';
}
